[tool.poetry]
name = "EyeTrackVR"
version = "0.2.0"
description = "Opensource, affordable VR eye tracker for VRChat"
authors = [
    "RedHawk989 <48768484+RedHawk989@users.noreply.github.com>",
    "ShyAssassin <49711232+ShyAssassin@users.noreply.github.com>"
]
license = "MIT"
repository = "https://github.com/RedHawk989/EyeTrackVR"

[tool.poetry.dependencies]
python = "~3.11.0"
python-osc = "^1.8.1"
opencv-python = "^4.6.0.66"
numpy = "^1.23.5"
pye3d = "^0.3.1.post1"
pydantic = "^1.10.2"
fastapi = "^0.89.1"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^5.6.2"
bandit = "^1.7.4"
black = "^22.10.0"
flake8 = "^5.0.4"
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 135
exclude = "(.git|.env|venv)"
target-version = ["py310","py311"]

[tool.bandit]
exclude_dirs = [".git", ".env", "venv", "tests"]